###  get all
GET http://localhost:3000/api/v1/user

### find by email a user
POST  http://localhost:3000/api/v1/user
Content-Type: application/json

{
  "email": "redosub@zi.se"
}

### update a user only wid session
PATCH  http://localhost:3000/api/v1/user
Content-Type: application/json

{
  "user_name": "Votuce",
  "url_img": "https://doodleipsum.com/700?i=33a195c3642aacda0dd669047297755c"
}

### Delete a account
DELETE http://localhost:3000/api/v1/user?id=11

# AUTH
### registerreate a user
POST  http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "email": "votuce@rupavaz.bf",
  "password": "123456"
}

### get session
POST  http://localhost:3000/api/v1/signing
Content-Type: application/json

{
  "email": "votuce@rupavaz.bf",
  "password": "votuce"
}

### signout session
GET http://localhost:3000/api/v1/signout