###  get all
GET http://localhost:3000/api/v1/user

### find by email a user
POST  http://localhost:3000/api/v1/user
Content-Type: application/json

{
  "email": "fidum@acidu.cv"
}

### update a user only wid session
PATCH  http://localhost:3000/api/v1/user
Content-Type: application/json

{
  "user_name": "fidum1"
}

### Disable profile
DELETE http://localhost:3000/api/v1/user?id=3

### verify account
GET  http://localhost:3000/api/v1/verify?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImloY29Ad2VqZS5wayIsImlhdCI6MTcxMDYwMjc4MywiZXhwIjoxNzExMjA3NTgzfQ.gpPkrv6HJUC2dTA6TWG3Ujd8PFXNe3jk_ijKP-jXSAc
-----------------------------------------------------------------
# AUTH
### register a user
POST  http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "email": "dabtut@jiufahu.mr",
  "password": "dabtut"
}

### get session
POST  http://localhost:3000/api/v1/signing
Content-Type: application/json

{
  "email": "fidum@acidu.cv",
  "password": "123456"
}

### signout session
GET http://localhost:3000/api/v1/signout
-----------------------------------------------------------------
### TASKS
# get all tasks
GET http://localhost:3000/api/v1/task

### get all tasks by query using author_id
GET http://localhost:3000/api/v1/task?author_id=2

### get tasks by id
GET http://localhost:3000/api/v1/task/6

### create a new task
POST  http://localhost:3000/api/v1/task
Content-Type: application/json

{
  "title": "create 3 refactor",
  "priority": 3,
  "due_date": "2024-03-16 23:11:33"
}

### update a new task
PATCH   http://localhost:3000/api/v1/task
Content-Type: application/json

{
  "id": 15,
  "title": "refact  15",
  "description": "Hay que cerrar el estadio!! 🎉",
  "due_date": "2024-03-16 23:11:33"
}

### delete a task
DELETE http://localhost:3000/api/v1/task?id=5
