###  get all
GET http://localhost:3000/api/v1/user

### find by email a user
POST  http://localhost:3000/api/v1/user
Content-Type: application/json

{
  "email": "votuce@rupavaz.bf"
}

### update a user only wid session
PATCH  http://localhost:3000/api/v1/user
Content-Type: application/json

{
  "user_name": "fuipo"
}

### Disable profile
DELETE http://localhost:3000/api/v1/user?id=11
-----------------------------------------------------------------
# AUTH
### register a user
POST  http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "email": "wog@da.et",
  "password": "wog123456"
}

### get session
POST  http://localhost:3000/api/v1/signing
Content-Type: application/json

{
  "email": "wog@da.et",
  "password": "wog123456"
}

### signout session
GET http://localhost:3000/api/v1/signout
-----------------------------------------------------------------
### TASKS
# get all tasks
GET http://localhost:3000/api/v1/task

### get all tasks by query using author_id
GET http://localhost:3000/api/v1/task?author_id=2

### get tasks by id
GET http://localhost:3000/api/v1/task/1

### create a new task
POST  http://localhost:3000/api/v1/task
Content-Type: application/json

{
  "title": "twtw test",
  "description": "felicidades genio!! 🎉",
  "priority": 2,
  "due_date": "2024-03-14 23:11:33"
}

### update a new task [TODO]
PATCH   http://localhost:3000/api/v1/task
Content-Type: application/json

{
  "id": 2,
  "title": "los genios hacen eso",
  "description": "Hay que cerrar el estadio!! 🎉",
  "due_date": "2024-03-16 23:11:33"
}
